### ISSUE TITLE
CRdroid 10.8 just came out :)

### ISSUE THREAD

**Issue by andiohn** [monefiera/Lenovo-Legion-Tab-GSI-FIX#1]
Also, it would be really nice to have a boot.img posted if that's possible? Thank you!!

**Comment by monefiera** [comment]
I have rewritten the readme a bit.
As for the boot.img, I can't provide it because I don't know which ZUI ROM you are using as a base (because of the risk of crashes).
I recommend that you extract the boot yourself, translating this article into English
https://smartasw.com/archives/15704

**Comment by monefiera** [comment]
> Also, it would be really nice to have a boot.img posted if that's possible? Thank you!!

I rewritted readme.md a bit.
As for the boot.img, I can't provide it because I don't know which ZUI ROM you are using as a base (because of the risk of critical crashes).
I recommend that you extract the boot yourself, translating this article into English.
https://smartasw.com/archives/15704
